# Generated by Django 2.1.3 on 2019-04-04 02:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Objetivos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Objetivos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
